### PR TITLE
Cleaned up and copyedited Chapter 7.

### PR DESCRIPTION
**Pull request by vertesians**
Chapter 7 had a *lot* of awkward repeated text, so I spent some time simplifying it and making it work the same way as everything else. The final output json went from 8.3 MiB down to 1.5 MiB so, um, yeah.

I also simplified the note on deriving diseases from roots, since it was also heavily repeated and awkward.

Lastly, while it's separate from the rest of the changes, I changed some of the notes in section 3.6 to be written more naturally/grammatically and to be clearer about the unofficialness of the added roots.

(... and everything was put into one giant commit because for some reason, my fork got disconnected from the repository, along with all the old PRs getting cleared out? I don't know what's up with that, but I had to re-fork and stick the files back in.)

### CODE REVIEW

**Comment by lomirus** [comment]
Hi, @vertesians. Sorry for the late response because I didn't notice this PR in this month until today.

As for the repeated text, actually, they are generated from a specific template by design out of @ryanlo713 's proposal. I am not sure which way is better and maybe you can talk with him.

> (... and everything was put into one giant commit because for some reason, my fork got disconnected from the repository, along with all the old PRs getting cleared out? I don't know what's up with that, but I had to re-fork and stick the files back in.)

Me, too 😅. My permission of repository was removed until I realized several days ago, and that's why I didn't receive the notification of this PR. The reason of both of these things is due to @ryanlo713 deleted this repository by mistake when he wanted to delete the repository he forked, but fortunately the repository was recovered eventually.

**Comment by ryanlo713** [comment]
Hey, @vertesians . Let me explain why we used templetes for dealing with those roots earlier. 

The main reason is that these roots listed in the original PDF file lack another root with a Specification pattern for reference.

I've seen your PR changes making good use of `see`, which is a good idea.

image

The secondary and less important reason is that it may facilitate other programs such as glosser to access the Specifications of these roots.

**Review by ryanlo713 — COMMENTED** [review]
Due to changes in the folder structure, you need to resolve branch conflicts first.

**Comment by ryanlo713** [comment]
Changes are migrated and integrated [here](https://github.com/yuorb/lexicon-json/pull/7) to avoid conflicts.

**Comment by vertesians** [comment]
No worries, I figured people were busy.

I'd strongly prefer using `see` instead of templates here, since the latter is just way too verbose, the templates were often ungrammatical because they just used simple substitution. They also created a lot of false positives while using a text search to retrieve entries.

(And more subjectively, I just found all that text hard to read.)

> The secondary and less important reason is that it may facilitate other programs such as glosser to access the Specifications of these roots.

I get what you mean, but programs have to support `see` either way since it's used in the rest of the lexicon. 

Anyway, since all of these changes got ported to the other PR, this one probably should be closed.

**Comment by lomirus** [comment]
Closed in favor of #7

**Pull request closed without merging**
